const CartActionTypes = {
    ADD_ITEM_WISHLIST: 'ADD_ITEM_WISHLIST',
    UPDATE_ITEM_WISHLIST: 'UPDATE_ITEM_WISHLIST',
    CLEAR_ITEM_FROM_CART_WISHLIST: 'CLEAR_ITEM_FROM_CART_WISHLIST',
    REMOVE_ITEM_WISHLIST: 'REMOVE_ITEM_WISHLIST'  
};

export default CartActionTypes;